.TH "s_data" 3 "Thu Jan 30 2025 17:36:41" "Push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_data \- Data structure, contains the two stacks and their lengths\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ft_pushswap\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_stack\fP * \fBa\fP"
.br
.ti -1c
.RI "size_t \fBa_len\fP"
.br
.ti -1c
.RI "\fBt_stack\fP * \fBb\fP"
.br
.ti -1c
.RI "size_t \fBb_len\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data structure, contains the two stacks and their lengths\&. 
.PP
Definition at line \fB55\fP of file \fBft_pushswap\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBt_stack\fP* a"

.PP
Definition at line \fB59\fP of file \fBft_pushswap\&.h\fP\&.
.SS "size_t a_len"

.PP
Definition at line \fB57\fP of file \fBft_pushswap\&.h\fP\&.
.SS "\fBt_stack\fP* b"

.PP
Definition at line \fB60\fP of file \fBft_pushswap\&.h\fP\&.
.SS "size_t b_len"

.PP
Definition at line \fB58\fP of file \fBft_pushswap\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Push_swap from the source code\&.
