.TH "s_sort_values" 3 "Thu Jan 30 2025 17:36:41" "Push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_sort_values
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfirst\fP"
.br
.ti -1c
.RI "int \fBfourth\fP"
.br
.ti -1c
.RI "int \fBsecond\fP"
.br
.ti -1c
.RI "int \fBthird\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBft_sort\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int first"

.PP
Definition at line \fB18\fP of file \fBft_sort\&.h\fP\&.
.SS "int fourth"

.PP
Definition at line \fB21\fP of file \fBft_sort\&.h\fP\&.
.SS "int second"

.PP
Definition at line \fB19\fP of file \fBft_sort\&.h\fP\&.
.SS "int third"

.PP
Definition at line \fB20\fP of file \fBft_sort\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Push_swap from the source code\&.
