.TH "s_stack" 3 "Thu Jan 30 2025 17:36:41" "Push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_stack \- Stack structure, doubly linked list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ft_pushswap\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_bool\fP \fBchecked\fP"
.br
.ti -1c
.RI "size_t \fBindex\fP"
.br
.ti -1c
.RI "struct \fBs_stack\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBs_stack\fP * \fBprev\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stack structure, doubly linked list\&. 
.PP
Definition at line \fB43\fP of file \fBft_pushswap\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBt_bool\fP checked"

.PP
Definition at line \fB49\fP of file \fBft_pushswap\&.h\fP\&.
.SS "size_t index"

.PP
Definition at line \fB47\fP of file \fBft_pushswap\&.h\fP\&.
.SS "struct \fBs_stack\fP* next"

.PP
Definition at line \fB46\fP of file \fBft_pushswap\&.h\fP\&.
.SS "struct \fBs_stack\fP* prev"

.PP
Definition at line \fB45\fP of file \fBft_pushswap\&.h\fP\&.
.SS "int value"

.PP
Definition at line \fB48\fP of file \fBft_pushswap\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Push_swap from the source code\&.
