.TH "Types" 3 "Thu Jan 30 2025 17:36:41" "Push_swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Types \- Data Types
.PP
 \- All the data types used in the project\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBs_data\fP"
.br
.RI "Data structure, contains the two stacks and their lengths\&. "
.ti -1c
.RI "struct \fBs_stack\fP"
.br
.RI "Stack structure, doubly linked list\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef char \fBt_bool\fP"
.br
.RI "Boolean type\&. "
.ti -1c
.RI "typedef struct \fBs_data\fP \fBt_data\fP"
.br
.RI "Data structure, contains the two stacks and their lengths\&. "
.ti -1c
.RI "typedef struct \fBs_stack\fP \fBt_stack\fP"
.br
.RI "Stack structure, doubly linked list\&. "
.in -1c
.SH "Detailed Description"
.PP 
All the data types used in the project\&. 


.SH "Typedef Documentation"
.PP 
.SS "typedef char \fBt_bool\fP"

.PP
Boolean type\&. 
.PP
Definition at line \fB38\fP of file \fBft_pushswap\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Push_swap from the source code\&.
